databases:
  - name: chiefonboardingdb
    databaseName: chiefonboardingdb
    ipAllowList: []

services:
  - type: web
    name: chiefonboarding
    env: docker
    dockerfilePath: ./back/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chiefonboardingdb
          property: connectionString
      - key: ACCOUNT_EMAIL
        sync: false
      - key: ACCOUNT_PASSWORD 
        sync: false
      - key: BASE_URL 
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SECRET_KEY
        generateValue: true
